
services:
  app:
    container_name: app_container 
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - jobboard_network
    volumes:
      - ./docs:/app/docs  
    depends_on:
      - psql_db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8080:8080"
    
    volumes:
      - ./docs:/usr/share/nginx/html/docs 
    environment:
      API_URL: /docs/swagger.yaml 
    depends_on:
      - app

  psql_db:
    container_name: psql_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    ports:
      - "5430:5432"
    networks:
      - jobboard_network

    environment:
        POSTGRES_PASSWORD: password

  redis:
    container_name: redis_container 
    image: redis
    ports:
      - 7979:6379
    networks:
      - jobboard_network

    
networks:
  jobboard_network:
    driver: bridge
   
volumes:

  postgres_data:
     driver: local