database:
  dbname: job_board
  pgurl: postgres://postgres:password@localhost:5430/job_board?sslmode=disable

server:
  host: localhost
  port: 8000

redis:
  host: localhost
  port: 7979

migration:
  path: internal/constant/query/schemas