database:
  dbname: job_board
  # pgurl: postgres://postgres:password@localhost:5432/job_board?sslmode=disable
  pgurl: postgres://postgres:password@psql_db:5432/job_board?sslmode=disable
server:
  host: localhost
  port: 8000

redis:
  host: localhost
  port: 7979

migration:
  path: internal/constant/query/schemas

authz:
  model: config/rabc_model.conf
  adapter: config/policy.csv
